apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: egyptian-map-pi
  labels:
    app: api-gateway
    part-of: egyptian-map-pi
    environment: production
spec:
  # High availability with 3 replicas across zones
  replicas: 3
  # Zero-downtime rolling updates
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
        environment: production
      annotations:
        # Prometheus monitoring integration
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
        # Config checksum for automatic pod updates when config changes
        checksum/config: "${CONFIG_CHECKSUM}"
    spec:
      containers:
      - name: api-gateway
        image: egyptian-map-pi/api-gateway:${VERSION}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
          name: http
        - containerPort: 9090
          name: metrics
        # Resource limits and requests for proper scheduling and resource management
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        # Health checking probes
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
        startupProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
        # Load configuration from ConfigMap
        envFrom:
        - configMapRef:
            name: api-gateway-config
        # Security context for container hardening
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop:
            - ALL
      # Pod anti-affinity for high availability across zones
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - api-gateway
              topologyKey: topology.kubernetes.io/zone
      # Grace period for proper shutdown
      terminationGracePeriodSeconds: 60