apiVersion: v1
kind: List
items:
# API Gateway Service Account - Critical Security Tier
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: api-gateway-sa
    namespace: app
    labels:
      app: egyptian-map-pi
      component: api-gateway
      tier: application
      version: v1
      istio-injection: enabled
      security-tier: critical
    annotations:
      iam.amazonaws.com/role: api-gateway-role
      prometheus.io/scrape: "true"
      security.compliance/last-audit: "2024-01-01T00:00:00Z"
      security.rotation/token-expiry: "24h"

# Auth Service Account - Critical Security Tier
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: auth-service-sa
    namespace: app
    labels:
      app: egyptian-map-pi
      component: auth-service
      tier: application
      version: v1
      istio-injection: enabled
      security-tier: critical
    annotations:
      iam.amazonaws.com/role: auth-service-role
      prometheus.io/scrape: "true"
      security.compliance/last-audit: "2024-01-01T00:00:00Z"
      security.rotation/token-expiry: "24h"

# Marketplace Service Account - High Security Tier
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: marketplace-service-sa
    namespace: app
    labels:
      app: egyptian-map-pi
      component: marketplace-service
      tier: application
      version: v1
      istio-injection: enabled
      security-tier: high
    annotations:
      iam.amazonaws.com/role: marketplace-service-role
      prometheus.io/scrape: "true"
      security.compliance/last-audit: "2024-01-01T00:00:00Z"
      security.rotation/token-expiry: "24h"

# Payment Service Account - Critical Security Tier with Shorter Token Rotation
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: payment-service-sa
    namespace: app
    labels:
      app: egyptian-map-pi
      component: payment-service
      tier: application
      version: v1
      istio-injection: enabled
      security-tier: critical
    annotations:
      iam.amazonaws.com/role: payment-service-role
      prometheus.io/scrape: "true"
      security.compliance/last-audit: "2024-01-01T00:00:00Z"
      security.rotation/token-expiry: "12h"

# Monitoring Service Account - Medium Security Tier
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: monitoring-sa
    namespace: monitoring
    labels:
      app: egyptian-map-pi
      component: monitoring
      tier: monitoring
      version: v1
      istio-injection: enabled
      security-tier: medium
    annotations:
      iam.amazonaws.com/role: monitoring-role
      prometheus.io/scrape: "true"
      security.compliance/last-audit: "2024-01-01T00:00:00Z"
      security.rotation/token-expiry: "48h"

# Storage Service Account - High Security Tier
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: storage-sa
    namespace: storage
    labels:
      app: egyptian-map-pi
      component: storage
      tier: storage
      version: v1
      istio-injection: enabled
      security-tier: high
    annotations:
      iam.amazonaws.com/role: storage-role
      prometheus.io/scrape: "true"
      security.compliance/last-audit: "2024-01-01T00:00:00Z"
      security.rotation/token-expiry: "24h"