# API Gateway Secrets
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: egyptian-map-pi
  labels:
    app: api-gateway
    part-of: egyptian-map-pi
    environment: production
    managed-by: terraform
  annotations:
    kubernetes.io/created-by: terraform
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "api-gateway"
    vault.hashicorp.com/secret-rotation: "true"
    vault.hashicorp.com/secret-rotation-period: "24h"
type: Opaque
data:
  jwt-private-key: ${JWT_PRIVATE_KEY}  # Base64 encoded JWT private key
  jwt-public-key: ${JWT_PUBLIC_KEY}    # Base64 encoded JWT public key
  audit-key: ${AUDIT_KEY}              # Base64 encoded audit encryption key
---
# Auth Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: auth-service-secrets
  namespace: egyptian-map-pi
  labels:
    app: auth-service
    part-of: egyptian-map-pi
    environment: production
    managed-by: terraform
  annotations:
    kubernetes.io/created-by: terraform
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "auth-service"
    vault.hashicorp.com/secret-rotation: "true"
    vault.hashicorp.com/secret-rotation-period: "168h"  # 7 days
type: Opaque
data:
  pi-network-api-key: ${PI_NETWORK_API_KEY}          # Base64 encoded Pi Network API key
  pi-network-api-secret: ${PI_NETWORK_API_SECRET}    # Base64 encoded Pi Network API secret
  kyc-encryption-key: ${KYC_ENCRYPTION_KEY}          # Base64 encoded KYC data encryption key
---
# Payment Service Secrets
apiVersion: v1
kind: Secret
metadata:
  name: payment-service-secrets
  namespace: egyptian-map-pi
  labels:
    app: payment-service
    part-of: egyptian-map-pi
    environment: production
    managed-by: terraform
  annotations:
    kubernetes.io/created-by: terraform
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "payment-service"
    vault.hashicorp.com/secret-rotation: "true"
    vault.hashicorp.com/secret-rotation-period: "168h"  # 7 days
    encryption.egyptian-map-pi.io/version: "v1"
type: Opaque
data:
  pi-network-payment-key: ${PI_NETWORK_PAYMENT_KEY}        # Base64 encoded Pi Network payment API key
  escrow-service-key: ${ESCROW_SERVICE_KEY}               # Base64 encoded escrow service key
  transaction-encryption-key: ${TRANSACTION_ENCRYPT_KEY}   # Base64 encoded transaction data encryption key